# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
defaults:
  -
    scope: 
      path: "_posts" # an empty string here means all files in the project
    values:
      layout: "default"
future: true
# Site settings
title: Liam Brannigan
email: braaannigan@gmail.com
description: Data Scientist
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://braaannigan.github.io/" # the base hostname & protocol for your site
twitter_username: braaannigan
github_username:  braaannigan


# Build settings
markdown: kramdown

me-img: "/img/mountain_yoga.jpg"

twitter-share: True
